# Generated by Django 5.2.13 on 2026-07-10 10:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_storyview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storyview',
            unique_together={('user', 'story')},
        ),
    ]
